### ISSUE TITLE
Add support to specify client cert and key files for authentication (kubelet --client-ca-file)

### ISSUE THREAD

**Issue by zmedico** [cyberark/kubeletctl#2]
If the [kubelet --client-ca-file option](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/#kubelet-authentication) is used to require a client certificate, then kubeletctl needs a way to specify client cert and key files (analogous to curl --cert and --key arguments).

**Comment by zmedico** [comment]
Acually, I see the support in 4948506b92a0337fe37405ecef64f1bdf6b9cc9f, so I'll give that a try. Thank you!

I got it working with a kubeconfig like this:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /path/to/ca.pem
    server: https://localhost:10250
  name: localhost-cluster
contexts:
- context:
    cluster: localhost-cluster
    user: localhost
  name: localhost-cluster
current-context: localhost-cluster
kind: Config
preferences: {}
users:
- name: localhost
  user:
    client-certificate: /path/to/cert.pem
    client-key: /path/to/key.pem

```
